### PR TITLE
dbProfile -> profile

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
The examples in the docs don't work because `profile` is returned instead of `dbProfile`.

### CODE REVIEW

**Comment by derhuerst** [comment]
Thanks for pointing this out!

Can you adapt the `import`s to still keep the profile's name in the variable? I think it makes the code slightly more understandable. E.g. `import {profile as dbProfile} from 'hafas-client/p/db/index.js'`. 🙏

**Comment by KristjanESPERANTO** [comment]
Ok, I adjusted it like this :slightly_smiling_face:

**Comment by KristjanESPERANTO** [comment]
I just stumbled across a typo, sorry. But now I should be done.

**Comment by derhuerst** [comment]
Thank you! I have squashed and merged your commits in d8805d9.

**Comment by KristjanESPERANTO** [comment]
Nice. Should I do an extra PR for the typo? I obviously committed it too late.

**Comment by derhuerst** [comment]
I have cherry-picked the typo fix as 1fdb7882.

**Pull request closed without merging**
