### PR TITLE
chore: improved performance

### PR DESCRIPTION
**Pull request by simlu**
closes https://github.com/public-transport/hafas-client/issues/146

### CODE REVIEW

**Comment by derhuerst** [comment]
> Looks like there is no eslint test (the formatting I've used should probably fail) [...]?

Please just follow the style specified in `.editorconfig`: use tabs for JavaScript. Other than that, I don't have strong (enough) opinions about the style to add ESLint, your code style is fine to me.

> Looks like [...] the e2e test also failed?

Yes, that is the currently the case, unfortunately. You didn't break it though, and the "unit" tests (using fixtures) are passing. Testing against actual live transit systems in a reliable way is really hard.

**Comment by simlu** [comment]
@derhuerst Sounds good. I did this pr on my phone, so didn't have tabs available...

Regarding e2e tests: Please take a look at node-tdd. It uses nock under the hook and should be exactly what you want for e2e testing (rerecord when necessary, but otherwise run against recordings). No need for stubbing as that is just a pain. We use node-tdd for thousands of tests and it is really well tested (and should be ok documented)

**Comment by simlu** [comment]
updated

**Comment by simlu** [comment]
Opened a ticked here regarding e2e for your consideration: https://github.com/public-transport/hafas-client/issues/148

**Comment by derhuerst** [comment]
Merged! 🎉 Do you want to mentioned in the [`contributors` section](https://github.com/public-transport/hafas-client/blob/cf69ff4bc817bb45f721ed98663adefcebbab593/package.json#L17-L19)? If yes, how?

**Comment by simlu** [comment]
@derhuerst All good. If I contribute more we can talk about it :)

**Pull request merged**
