### PR TITLE
Add routingModes option to db profile

### PR DESCRIPTION
**Pull request by lamBOOO**
Sorry for the delay, but I started working on #287. It seems to work so far.

I'm a little confused with the testing, so I "only" added an e2e to test all different routingMode options for errors.

Is the testing done properly?

### CODE REVIEW

**Comment by derhuerst** [comment]
Thanks!

I have squashed your commits into one, and adapted that one commit slightly:

- moved `lib/db-routing-modes.js` to `p/db/routing-modes` (if it's DB-specific, let's put it in `p/db`; if it's not, let's rename it and put it in `lib`)
- added a integration test fixture (which is just a set of recorded E2E test HTTP requests)
- minor code formatting

**Comment by lamBOOO** [comment]
Thank you. 👍

Just for understanding: The integration test fixture is generated by "simply" running the `test-integration:record` script and then pushing the updated `recording.har` into the repo? 🤔

**Comment by derhuerst** [comment]
> The integration test fixture is generated by "simply" running the `test-integration:record` script and then pushing the updated `recording.har` into the repo? 🤔

Yes, although – as you have pointed out – running `test-integration:record` will fail in practice because most test suites/files' `T_MOCK` are in the past, so querying new HTTP responses from HAFAS won't work.

I have documented some of the gotchas of the testing setup in 19cdde06. If you have more questions (or even want to contribute more guidance), don't hesitate to create a new Issue!

**Comment by lamBOOO** [comment]
Thanks, it's now more clear to me. My initial starting point for testing/contribution was the `contributing.md`.

great work btw 👍

**Pull request closed without merging**
