### PR TITLE
Nah.sh: enable radar

### PR DESCRIPTION
**Pull request by derhuerst**
despite the failing and skipped test (see also #34).

We can make this specific test handle missing station names and products, if we want. Or we fix this along with the tests rewrite.

### CODE REVIEW

**Comment by juliuste** [comment]
We should un-`tape.skip` the radar test as well. Could you do that?

**Comment by derhuerst** [comment]
I've fixed it now. What a mess!

**Comment by juliuste** [comment]
Can this be merged?

**Comment by derhuerst** [comment]
if you're happy with the code, yes

**Comment by juliuste** [comment]
👍

**Pull request merged**
