### PR TITLE
handle next-day legs on overnight journeys

### LINKED ISSUE #301: wrong date parsed for next-day DEVI legs on overnight journeys
When a journey starts in the evening, and one leg of the journey is completely in the next day, this leg gets assigned the date of the departure day, not the arrival day.

This results in applications like bahn.guru reporting a negative travel time, since according to hafas-client you arrive on the same day early in the morning, instead of the next day early in the morning: https://github.com/juliuste/bahn.guru/issues/35

I'm not yet sure how to fix this, but I've successfully reproduced it with a test. I'll therefore open a PR which showcases the problem. Not sure if and when I'm able to fix this, so feel free to take over if you already know how to fix it.

### PR DESCRIPTION
**Pull request by soerface**
Fix #301 (currently just reproducing it). I'm not yet sure how to fix it and will need some time to figure it out. Feel free to take over.

### CODE REVIEW

**Comment by derhuerst** [comment]
It's been a while since I looked at this. Do you know if there is anything missing here? 🤔

**Comment by soerface** [comment]
Me too :sweat_smile: I'm not familiar with the library, but since the tests we wrote are now green, I guess that this can be merged?

**Comment by derhuerst** [comment]
Do you want to be mentioned as a [contributor](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#people-fields-author-contributors) in `package.json`? If you do, how? As `Soeren Wegener <wegener92@gmail.com>`? As `soerface`?

**Comment by soerface** [comment]
@derhuerst Thank you very much for the offer :blush:! You can use `Sören Wegener (https://soerface.de/)`

**Pull request merged**
