### PR TITLE
parse 'Q' hints

### PR DESCRIPTION
**Pull request by debfx**
Parse 'Q' hints. They seem to contain changes to the features of a train.

Some examples:
```
{"type":"Q","code":"","icoX":5,"txtN":"RE 10618: Düsseldorf Hbf - Neuss Hbf: Information. Heute: Mehrzweckabteil hinten","sIdx":0}
{"type":"Q","code":"","icoX":7,"txtN":"RE 10657: Köln/Bonn Flughafen - Duisburg Hbf: Information. Keine behindertengerechte Einrichtung","sIdx":0}
{"type":"Q","code":"","icoX":8,"txtN":"RE 19927: Stuttgart Hbf - Winnenden: Information. Störung fahrzeuggebundene Einstiegshilfe","sIdx":0}
{"type":"Q","code":"","icoX":6,"txtN":"S      1: Hilden Süd - Düsseldorf Hbf: Information. Ein Wagen fehlt","sIdx":0}
```

### CODE REVIEW

**Comment by derhuerst** [comment]
Which endpoints do you have these from?

**Comment by debfx** [comment]
These are all from the DB endpoint.

**Comment by derhuerst** [comment]
Do you know if the other endpoints use `Q` remarks as well?

**Comment by debfx** [comment]
Sorry, I haven't used the other endpoints at all yet.

**Pull request merged**
